clc; 
clear all; 
close all; 
fs=8000;
fm=50;
fc=1500; 
Am=2; 
Ac=2;
t=[0:0.1*fs]/fs; 
m=Am*cos(2*pi*fm*t);
c=Ac*cos(2*pi*fc*t);
s=Ac*m.*cos(2*pi*fc*t);
subplot(4,1,1); 
plot(t,m,'b');
title('Message Signal');
xlabel('time(sec)');
ylabel('Amplitude(v)');
subplot(4,1,2); 
plot(t,c,'r');
title('Carrier Signal');
xlabel('time(sec)');
ylabel('Amplitude(v)');
subplot(4,1,3); 
plot(t,s,'g');
title('Modulated Signal of DSB-SC');
xlabel('time(sec)');
ylabel('Amplitude(v)');
d=s.*c;
[b,a] = butter(1,0.01,'low');
d1= filter(b,a,d);
subplot(4,1,4); 
plot(t,d1,'b');
title('Demodulated Signal of DSB-SC');
xlabel('time(sec)');
ylabel('Amplitude(v)');
grid on;