clc;
close all;
clear all;
fs=1000;
N=2012;
t=[0:N-1]/fs;
x = sin(2*pi*20*t);
subplot(4,1,1);
plot(t,x,'r');
axis([0 0.05 -1 1]);
axis tight;
xlabel('Time');
ylabel('Amplitude');
title('Input Signal');
x1=fft(x);
k=0:N-1;
Xmag=abs(x1);
subplot(4,1,2);
plot(k,Xmag,'g');
axis tight;
xlabel('Frequency');
ylabel('Amplitude');
title('Magnitude of the fft signal');
Xphase=angle(x1)*(180/pi);
subplot(4,1,3);
plot(k,Xphase,'k');
grid on;
xlabel('Frequency');
ylabel('Angle');
title('Phase of the fft signal');
axis tight;
c=ifft(x1);
subplot(4,1,4);
plot(t,c,'m');
grid on;
xlabel('Time');
ylabel('Amplitude');
title('Magnitude of the inverse fft signal');
axis tight;
